nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

packageExtensions:
  '@firebase/analytics@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/app-check@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/auth@*':
    dependencies:
      '@firebase/app': '*'
      '@firebase/app-types': '*'
  '@firebase/auth-types@*':
    dependencies:
      '@firebase/app-types': '*'
  '@firebase/firestore@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/firestore-types@*':
    dependencies:
      '@firebase/app-types': '*'
  '@firebase/functions@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/installations@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/installations-types@*':
    dependencies:
      '@firebase/app-types': '*'
  '@firebase/messaging@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/performance@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/remote-config@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/storage@*':
    dependencies:
      '@firebase/app': '*'
  '@firebase/storage-types@*':
    dependencies:
      '@firebase/app-types': '*'
  '@tiptap/starter-kit@*':
    dependencies:
      '@tiptap/pm': '*'
